import { useRouter } from "next/router";
import Favorits from "@/components/Favorits";
import Recents from "@/components/Recents";
import Permissions from "@/components/Permissions";
import Personal from "@/components/Personal";
import Sharing from "@/components/Sharing";
import MyDrive from "@/components/MyDrive";
import PersistentDrawerLeft from "@/components/LeftBarNavigation";
import { useEffect, useState } from "react";
import Header from "@/components/Header";
import { Box, CssBaseline, Toolbar } from "@mui/material";
import Head from "next/head";

const Drive = () => {
    const router = useRouter();
    const [open, setOpen] = useState(true);
    const driveRoutes = [
        {
            itemName:"favorits", 
            itemComponent:<Favorits/>
        },
        {
            itemName:"recents", 
            itemComponent:<Recents/>
        },
        {
            itemName:"permissions", 
            itemComponent:<Permissions/>
        },
        {
            itemName:"personal", 
            itemComponent:(<Personal/>)
        },
        {
            itemName:"sharing", 
            itemComponent:<Sharing/>
        },
        {
            itemName:"my-drive",
            itemComponent:<MyDrive/>
        }
    ]
    const [currentpage, setCurrentPage] = useState(<Personal/>)
  
    useEffect(() => {
      if (driveRoutes.find((element)=>element.itemName === router.query.slug) === undefined) {
          router.push("/drive/personal")
      }
      setCurrentPage(currentPageBySlug(router.query.slug))
    }, [router]);

    const handleDrawer = () => {
        setOpen(!open);
      };

    const currentPageBySlug = (pathname) => {
        const component = driveRoutes.find((element)=>element.itemName === pathname)
        if(component !== undefined){
            return component.itemComponent
        }
    }

    return (  
        <>
            <Head>
                <title>Economic Drive</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{ display: 'flex' }}>
                <CssBaseline />
                <Header handleDrawer={handleDrawer}/>   
                <PersistentDrawerLeft currentPage={router.query.slug} open={open}/>
                <Box component="main" sx={{ flexGrow: 1 }}>
                <Toolbar />
                {
                    currentpage
                }
                </Box>
            </Box>
        </>
    );
}
 
export default Drive;